version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install &&
             npm start"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider